on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited
jobs:
  check_labels:
    runs-on: ubuntu-latest
    name: Check required labels and title
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PR Checker
        uses: ./
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          jira_title_regex: ^\[(([A-Z][A-Z0-9]+-[0-9]+)|NOJIRA)\]
          required_labels: "feature,bug,documentation,chore"
